version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wired-ai
    environment:
      - MILVUS_HOST=192.168.3.169
      - MILVUS_PORT=19530
      - OPEN_AI_KEY=sk-xxxxxxxxxxxxxxxxxxxxxxxxxxx
      - REDIS_IS_CLUSTER=false
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    ports:
      - 8888:8765
    logging:
        driver: "json-file"
        options:
            max-size: "5g"
    volumes:
      - "/tmp/log/wired-ai:/app/log"
      - "/tmp/wired-ai:/tmp"